# Generated by Django 6.1.2 on 2026-10-10 00:42

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monedas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('direccion', models.CharField(max_length=255)),
                ('activa', models.BooleanField(db_index=True, default=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'sucursal',
                'verbose_name_plural': 'sucursales',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('sucursal', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='caja', to='cajas.sucursal')),
            ],
            options={
                'verbose_name': 'caja',
                'verbose_name_plural': 'cajas',
            },
        ),
        migrations.CreateModel(
            name='FondoCajero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fondos_cajeros', to='cajas.caja')),
                ('cajero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fondos_cajero', to=settings.AUTH_USER_MODEL)),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='monedas.moneda')),
            ],
            options={
                'verbose_name': 'fondo de cajero',
                'verbose_name_plural': 'fondos de cajeros',
                'ordering': ['cajero__username', 'moneda__codigo'],
                'constraints': [models.UniqueConstraint(fields=('caja', 'cajero', 'moneda'), name='fondo_cajero_moneda_unico'), models.CheckConstraint(condition=models.Q(('saldo__gte', 0)), name='fondo_cajero_no_negativo')],
            },
        ),
        migrations.CreateModel(
            name='MovimientoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INGRESO', 'Ingreso a caja'), ('RETIRO', 'Retiro de caja'), ('ASIGNACION', 'Asignación a cajero'), ('DEVOLUCION', 'Devolución de cajero')], max_length=12)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('saldo_caja_resultante', models.DecimalField(decimal_places=2, max_digits=18)),
                ('saldo_cajero_resultante', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('nota', models.CharField(blank=True, max_length=255)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='cajas.caja')),
                ('cajero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_caja', to=settings.AUTH_USER_MODEL)),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='monedas.moneda')),
                ('realizado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_caja_realizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'movimiento de caja',
                'verbose_name_plural': 'movimientos de caja',
                'ordering': ['-creado_en', '-pk'],
                'constraints': [models.CheckConstraint(condition=models.Q(('importe__gt', 0)), name='movimiento_caja_importe_positivo')],
            },
        ),
        migrations.CreateModel(
            name='SaldoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saldos', to='cajas.caja')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='monedas.moneda')),
            ],
            options={
                'verbose_name': 'saldo de caja',
                'verbose_name_plural': 'saldos de caja',
                'ordering': ['moneda__codigo'],
                'constraints': [models.UniqueConstraint(fields=('caja', 'moneda'), name='saldo_caja_moneda_unico'), models.CheckConstraint(condition=models.Q(('saldo__gte', 0)), name='saldo_caja_no_negativo')],
            },
        ),
    ]
