# Generated by Django 6.1.2 on 2026-10-10 02:37

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cajas', '0001_initial'),
        ('monedas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConteoInventarioBilletes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importe_total', models.DecimalField(decimal_places=2, max_digits=18)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conteos_billetes', to='cajas.caja')),
                ('cajero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conteos_inventario_billetes', to=settings.AUTH_USER_MODEL)),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='monedas.moneda')),
                ('realizado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conteos_billetes_realizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'conteo de inventario de billetes',
                'verbose_name_plural': 'conteos de inventario de billetes',
                'ordering': ['-creado_en', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='DenominacionBillete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='denominaciones_billetes', to='monedas.moneda')),
            ],
            options={
                'verbose_name': 'denominación de billete',
                'verbose_name_plural': 'denominaciones de billetes',
                'ordering': ['moneda__codigo', '-valor'],
            },
        ),
        migrations.CreateModel(
            name='DetalleConteoInventarioBilletes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('conteo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalle_billetes', to='cajas.conteoinventariobilletes')),
                ('denominacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cajas.denominacionbillete')),
            ],
            options={
                'ordering': ['-denominacion__valor'],
            },
        ),
        migrations.CreateModel(
            name='DetalleMovimientoBillete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('denominacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cajas.denominacionbillete')),
                ('movimiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalle_billetes', to='cajas.movimientocaja')),
            ],
            options={
                'verbose_name': 'detalle de billetes del movimiento',
                'verbose_name_plural': 'detalles de billetes del movimiento',
                'ordering': ['-denominacion__valor'],
            },
        ),
        migrations.CreateModel(
            name='InventarioBilleteCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventario_billetes', to='cajas.caja')),
                ('denominacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cajas.denominacionbillete')),
            ],
            options={
                'verbose_name': 'existencia de billetes en caja',
                'verbose_name_plural': 'existencias de billetes en caja',
                'ordering': ['denominacion__moneda__codigo', '-denominacion__valor'],
            },
        ),
        migrations.CreateModel(
            name='InventarioBilleteCajero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventario_billetes_cajeros', to='cajas.caja')),
                ('cajero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventario_billetes_cajero', to=settings.AUTH_USER_MODEL)),
                ('denominacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cajas.denominacionbillete')),
            ],
            options={
                'verbose_name': 'existencia de billetes de cajero',
                'verbose_name_plural': 'existencias de billetes de cajeros',
                'ordering': ['cajero__username', 'denominacion__moneda__codigo', '-denominacion__valor'],
            },
        ),
        migrations.AddConstraint(
            model_name='denominacionbillete',
            constraint=models.UniqueConstraint(fields=('moneda', 'valor'), name='denominacion_billete_moneda_valor'),
        ),
        migrations.AddConstraint(
            model_name='denominacionbillete',
            constraint=models.CheckConstraint(condition=models.Q(('valor__gt', 0)), name='denominacion_billete_valor_positivo'),
        ),
        migrations.AddConstraint(
            model_name='detalleconteoinventariobilletes',
            constraint=models.UniqueConstraint(fields=('conteo', 'denominacion'), name='detalle_conteo_billete_unico'),
        ),
        migrations.AddConstraint(
            model_name='detalleconteoinventariobilletes',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='detalle_conteo_billete_cantidad_positiva'),
        ),
        migrations.AddConstraint(
            model_name='detallemovimientobillete',
            constraint=models.UniqueConstraint(fields=('movimiento', 'denominacion'), name='detalle_movimiento_billete_unico'),
        ),
        migrations.AddConstraint(
            model_name='detallemovimientobillete',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='detalle_movimiento_billete_cantidad_positiva'),
        ),
        migrations.AddConstraint(
            model_name='inventariobilletecaja',
            constraint=models.UniqueConstraint(fields=('caja', 'denominacion'), name='inventario_billete_caja_unico'),
        ),
        migrations.AddConstraint(
            model_name='inventariobilletecajero',
            constraint=models.UniqueConstraint(fields=('caja', 'cajero', 'denominacion'), name='inventario_billete_cajero_unico'),
        ),
    ]
