# Generated by Django 6.1.1 on 2026-10-08 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasa_cambios', '0002_alter_tasacambio_tasa_compra_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CAMBIO_TASA', 'Cambio de tasa de cambio')], max_length=20)),
                ('mensaje', models.CharField(max_length=500)),
                ('leida', models.BooleanField(default=False)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('tasa', models.ForeignKey(blank=True, help_text='De qué tasa se trata, para poder reconstruir el cambio.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notificaciones', to='tasa_cambios.tasacambio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'notificación',
                'verbose_name_plural': 'notificaciones',
                'ordering': ['-creada_en'],
            },
        ),
    ]
