# Generated by Django 6.1.1 on 2026-09-06 13:36

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monedas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TasaCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasa_compra', models.DecimalField(decimal_places=6, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))])),
                ('tasa_venta', models.DecimalField(decimal_places=6, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))])),
                ('vigente_desde', models.DateTimeField()),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('moneda_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasas_como_destino', to='monedas.moneda')),
                ('moneda_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasas_como_origen', to='monedas.moneda')),
            ],
            options={
                'verbose_name': 'tasa de cambio',
                'verbose_name_plural': 'tasas de cambio',
                'ordering': ['-vigente_desde'],
                'constraints': [models.CheckConstraint(condition=models.Q(('moneda_origen', models.F('moneda_destino')), _negated=True), name='tasa_cambio_monedas_diferentes'), models.CheckConstraint(condition=models.Q(('tasa_compra__gt', 0)), name='tasa_cambio_compra_positiva'), models.CheckConstraint(condition=models.Q(('tasa_venta__gt', 0)), name='tasa_cambio_venta_positiva'), models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('moneda_origen', 'moneda_destino'), name='tasa_cambio_unica_activa_por_par')],
            },
        ),
    ]
