# Generated by Django 6.1.1 on 2026-09-06 16:48

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasa_cambios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasacambio',
            name='tasa_compra',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='tasacambio',
            name='tasa_venta',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
