# Generated by Django 6.1.1 on 2026-09-05 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0005_alter_cliente_categoria_asociacionusuariocliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('BANCARIA', 'Cuenta bancaria'), ('BILLETERA', 'Billetera electrónica')], max_length=10)),
                ('entidad', models.CharField(help_text='Banco (ej. Banco Itaú) o billetera (ej. Tigo Money).', max_length=100)),
                ('numero_cuenta', models.CharField(max_length=30, verbose_name='Número de cuenta / teléfono')),
                ('titular', models.CharField(max_length=150)),
                ('alias', models.CharField(blank=True, max_length=50)),
                ('activa', models.BooleanField(db_index=True, default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas_pago', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'cuenta de pago',
                'verbose_name_plural': 'cuentas de pago',
                'ordering': ['-creado_en'],
                'constraints': [models.UniqueConstraint(fields=('cliente', 'entidad', 'numero_cuenta'), name='cuenta_pago_unica_por_cliente')],
            },
        ),
    ]
