# Generated by Django 6.1 on 2026-08-29 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_documento_alter_cliente_ruc'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='activo',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
