# Generated by Django 6.1 on 2026-08-30 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_cliente_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='categoria',
            field=models.CharField(choices=[('MINORISTA', 'Minorista'), ('CORPORATIVO', 'Corporativo'), ('VIP', 'VIP')], default='MINORISTA', max_length=20),
        ),
    ]
