# Generated by Django 6.1 on 2026-08-30 23:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_cliente_categoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='categoria',
            field=models.CharField(blank=True, choices=[('MINORISTA', 'Minorista'), ('CORPORATIVO', 'Corporativo'), ('VIP', 'VIP')], default='MINORISTA', max_length=20),
        ),
        migrations.CreateModel(
            name='AsociacionUsuarioCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asociaciones_usuarios', to='clientes.cliente')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asociaciones_clientes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'asociación usuario-cliente',
                'verbose_name_plural': 'asociaciones usuario-cliente',
                'ordering': ['usuario__username', 'cliente__creado_en'],
                'constraints': [models.UniqueConstraint(fields=('usuario', 'cliente'), name='asociacion_usuario_cliente_unica')],
            },
        ),
    ]
