# Generated by Django 6.1.1 on 2026-10-10 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conversiones', '0005_alter_compradivisa_estado_alter_ventadivisa_estado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor', models.CharField(max_length=20)),
                ('id_externo', models.CharField(blank=True, max_length=100)),
                ('order_id', models.CharField(max_length=60, unique=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=16)),
                ('moneda', models.CharField(max_length=3)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('REEMBOLSADO', 'Reembolsado'), ('REQUIERE_REVISION', 'Requiere revisión manual')], default='PENDIENTE', max_length=20)),
                ('redirect_url', models.URLField(blank=True)),
                ('respuesta_cruda', models.JSONField(blank=True, default=dict, help_text='Respuesta de la pasarela, sin claves ni cabeceras de autenticación.')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='conversiones.compradivisa')),
                ('venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='conversiones.ventadivisa')),
            ],
            options={
                'verbose_name': 'pago',
                'verbose_name_plural': 'pagos',
                'ordering': ['-creado_en'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('compra__isnull', False), ('venta__isnull', True)), models.Q(('compra__isnull', True), ('venta__isnull', False)), _connector='OR'), name='pago_pertenece_a_una_sola_operacion')],
            },
        ),
    ]
