# Generated by Django 5.2 on 2026-09-27

import decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("clientes", "0005_alter_cliente_categoria_asociacionusuariocliente"),
        ("monedas", "0001_initial"),
        ("tasa_cambios", "0002_alter_tasacambio_tasa_compra_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompraDivisa",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("monto_pagado", models.DecimalField(decimal_places=2, help_text="Importe base indicado por el cliente, sin comisión.", max_digits=16, validators=[django.core.validators.MinValueValidator(decimal.Decimal("0.01"))])),
                ("porcentaje_comision", models.DecimalField(decimal_places=2, max_digits=5)),
                ("monto_comision", models.DecimalField(decimal_places=2, max_digits=16)),
                ("total_a_pagar", models.DecimalField(decimal_places=2, max_digits=16)),
                ("tasa_aplicada", models.DecimalField(decimal_places=2, max_digits=12)),
                ("monto_recibido", models.DecimalField(decimal_places=2, max_digits=18)),
                ("confirmado_en", models.DateTimeField(auto_now_add=True)),
                ("cliente", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="compras_divisas", to="clientes.cliente")),
                ("moneda_adquirida", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="compras_como_moneda_adquirida", to="monedas.moneda")),
                ("moneda_pagada", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="compras_como_moneda_pagada", to="monedas.moneda")),
                ("tasa_cambio", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="compras_confirmadas", to="tasa_cambios.tasacambio")),
            ],
            options={"verbose_name": "compra de divisa", "verbose_name_plural": "compras de divisas", "ordering": ["-confirmado_en"]},
        ),
        migrations.AddConstraint(
            model_name="compradivisa",
            constraint=models.CheckConstraint(condition=models.Q(("moneda_pagada", models.F("moneda_adquirida")), _negated=True), name="compra_divisa_monedas_diferentes"),
        ),
    ]
