# Generated by Django 6.1.1 on 2026-09-28 22:46

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_alter_cliente_categoria_asociacionusuariocliente'),
        ('conversiones', '0001_compra_divisa'),
        ('cuentas', '0001_initial'),
        ('monedas', '0001_initial'),
        ('tasa_cambios', '0002_alter_tasacambio_tasa_compra_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VentaDivisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_entregado', models.DecimalField(decimal_places=2, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('porcentaje_comision', models.DecimalField(decimal_places=2, max_digits=5)),
                ('monto_comision', models.DecimalField(decimal_places=2, max_digits=18)),
                ('monto_convertido', models.DecimalField(decimal_places=2, max_digits=18)),
                ('monto_acreditado', models.DecimalField(decimal_places=2, max_digits=18)),
                ('tasa_aplicada', models.DecimalField(decimal_places=2, max_digits=12)),
                ('confirmado_en', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas_divisas', to='clientes.cliente')),
                ('cuenta_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas_divisas', to='cuentas.cuentapago')),
                ('moneda_acreditada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas_como_moneda_acreditada', to='monedas.moneda')),
                ('moneda_entregada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas_como_moneda_entregada', to='monedas.moneda')),
                ('tasa_cambio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas_confirmadas', to='tasa_cambios.tasacambio')),
            ],
            options={
                'verbose_name': 'venta de divisa',
                'verbose_name_plural': 'ventas de divisas',
                'ordering': ['-confirmado_en'],
                'constraints': [models.CheckConstraint(condition=models.Q(('moneda_entregada', models.F('moneda_acreditada')), _negated=True), name='venta_divisa_monedas_diferentes')],
            },
        ),
    ]
