# Generated by Django 6.1.1 on 2026-09-30 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversiones', '0003_estado_pendiente_cancelacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compradivisa',
            name='motivo_cancelacion',
            field=models.CharField(blank=True, choices=[('CAMBIO_COTIZACION', 'La cotización cambió antes de confirmar'), ('CLIENTE', 'Cancelada por el cliente'), ('EXPIRADA', 'Se venció el tiempo para confirmar')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ventadivisa',
            name='motivo_cancelacion',
            field=models.CharField(blank=True, choices=[('CAMBIO_COTIZACION', 'La cotización cambió antes de confirmar'), ('CLIENTE', 'Cancelada por el cliente'), ('EXPIRADA', 'Se venció el tiempo para confirmar')], max_length=20),
        ),
    ]
