# Generated by Django 6.1.1 on 2026-10-08 17:29
#
# Se agregó a mano la migración de datos del final (RF023 — GEG9-37): crea un
# CambioEstado inicial para cada compra/venta que ya existía antes de este
# cambio, para que ninguna operación vieja quede sin historial.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def crear_historial_inicial(apps, schema_editor):
    CompraDivisa = apps.get_model("conversiones", "CompraDivisa")
    VentaDivisa = apps.get_model("conversiones", "VentaDivisa")
    CambioEstado = apps.get_model("conversiones", "CambioEstado")

    for compra in CompraDivisa.objects.all():
        cambio = CambioEstado.objects.create(
            compra=compra, estado_anterior="", estado_nuevo=compra.estado,
        )
        cambio.fecha = compra.confirmado_en or compra.cancelado_en or compra.creado_en
        cambio.save(update_fields=["fecha"])

    for venta in VentaDivisa.objects.all():
        cambio = CambioEstado.objects.create(
            venta=venta, estado_anterior="", estado_nuevo=venta.estado,
        )
        cambio.fecha = venta.confirmado_en or venta.cancelado_en or venta.creado_en
        cambio.save(update_fields=["fecha"])


def revertir(apps, schema_editor):
    """No hace falta deshacer nada: el modelo se borra solo al revertir CreateModel."""


class Migration(migrations.Migration):

    dependencies = [
        ('conversiones', '0004_alter_compradivisa_motivo_cancelacion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='compradivisa',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de confirmación'), ('CONFIRMADA', 'Pagada'), ('CANCELADA', 'Cancelada'), ('ANULADA', 'Anulada')], default='PENDIENTE', max_length=12),
        ),
        migrations.AlterField(
            model_name='ventadivisa',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de confirmación'), ('CONFIRMADA', 'Pagada'), ('CANCELADA', 'Cancelada'), ('ANULADA', 'Anulada')], default='PENDIENTE', max_length=12),
        ),
        migrations.CreateModel(
            name='CambioEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(blank=True, choices=[('PENDIENTE', 'Pendiente de confirmación'), ('CONFIRMADA', 'Pagada'), ('CANCELADA', 'Cancelada'), ('ANULADA', 'Anulada')], max_length=12)),
                ('estado_nuevo', models.CharField(choices=[('PENDIENTE', 'Pendiente de confirmación'), ('CONFIRMADA', 'Pagada'), ('CANCELADA', 'Cancelada'), ('ANULADA', 'Anulada')], max_length=12)),
                ('motivo', models.CharField(blank=True, max_length=255)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cambios_estado', to='conversiones.compradivisa')),
                ('usuario', models.ForeignKey(blank=True, help_text='Vacío si el cambio lo hizo el sistema (por ejemplo, al vencerse el plazo).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cambios_estado_conversiones', to=settings.AUTH_USER_MODEL)),
                ('venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cambios_estado', to='conversiones.ventadivisa')),
            ],
            options={
                'verbose_name': 'cambio de estado',
                'verbose_name_plural': 'cambios de estado',
                'ordering': ['fecha'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('compra__isnull', False), ('venta__isnull', True)), models.Q(('compra__isnull', True), ('venta__isnull', False)), _connector='OR'), name='cambio_estado_pertenece_a_una_sola_operacion')],
            },
        ),
        migrations.RunPython(crear_historial_inicial, revertir),
    ]
